#!/usr/bin/env bash
# Refresh the README.md dashboard block by querying each child repo's
# latest release via gh. Runs in the umbrella repo working dir.
set -euo pipefail

ORG="AmericanGroupLLC"
REPOS=(
  "DriftDate"
  "Offline-AI-Buddy"
  "HealthApp"
  "ClockApp"
  "Card"
  "BuddyPlay"
  "AmericanGroupLLC.github.io"
)

START="<!-- DASHBOARD_START -->"
END="<!-- DASHBOARD_END -->"

if [ ! -f README.md ]; then
  echo "::error::README.md not found in umbrella repo" >&2
  exit 1
fi
if ! grep -q "$START" README.md || ! grep -q "$END" README.md; then
  echo "::warning::README.md missing dashboard markers; appending block."
  printf '\n\n%s\n%s\n' "$START" "$END" >> README.md
fi

TMP="$(mktemp)"
{
  echo "$START"
  echo "<!-- Auto-generated by .github/workflows/release-dashboard.yml. Do not edit. -->"
  echo ""
  echo "## 📊 Release Dashboard"
  echo ""
  echo "_Updated: $(date -u +'%Y-%m-%d %H:%M UTC')_"
  echo ""
  echo "| Repository | Latest Release | Published | Notes |"
  echo "|---|---|---|---|"
  for r in "${REPOS[@]}"; do
    rel_json=""
    if command -v gh >/dev/null 2>&1; then
      rel_json=$(gh api -H "Accept: application/vnd.github+json" \
        "repos/$ORG/$r/releases/latest" 2>/dev/null || echo "")
    fi
    if [ -z "$rel_json" ] || echo "$rel_json" | grep -q '"message".*"Not Found"'; then
      echo "| [$r](https://github.com/$ORG/$r) | — | — | _no releases yet_ |"
    else
      tag=$(echo "$rel_json" | jq -r '.tag_name // "—"')
      pub=$(echo "$rel_json" | jq -r '.published_at // ""' | cut -c1-10)
      url=$(echo "$rel_json" | jq -r '.html_url // ""')
      [ -z "$pub" ] && pub="—"
      if [ -n "$url" ] && [ "$tag" != "—" ]; then
        echo "| [$r](https://github.com/$ORG/$r) | [$tag]($url) | $pub | |"
      else
        echo "| [$r](https://github.com/$ORG/$r) | $tag | $pub | |"
      fi
    fi
  done
  echo ""
  echo "$END"
} > "$TMP"

awk -v start="$START" -v end="$END" -v block_file="$TMP" '
  BEGIN { skipping = 0 }
  index($0, start) {
    if (!printed) {
      while ((getline line < block_file) > 0) print line
      close(block_file)
      printed = 1
    }
    skipping = 1
    next
  }
  skipping && index($0, end) { skipping = 0; next }
  !skipping { print }
' README.md > README.md.new
mv README.md.new README.md
echo "Dashboard block refreshed."
